#!/bin/sh
#
# @name iris_silk SITL
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MC_PITCHRATE_P 0.1
param set-default MC_ROLLRATE_P 0.05

set PWM_OUT 12345678
set MIXER quad_x_silk

